language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  
install: 
  - sudo apt-get install g++-7

script:
  - cd GameDevProjects/01HelloBuildProject
  - mkdir build
  - cd build
  - cmake ..  && make
