dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2
