sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - sudo apt-get update -qq

script:
  - cd GameDevProjects/01HelloBuildProject
  - mkdir build
  - cd build
  - cmake ../  && make
