sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - cd GameDevProjects/01HelloBuildProject
  - mkdir build
  - cd build
  - cmake ..  && make
